spring:
  data:
    mongodb:
      host: 172.30.192.1
      port: 27017
      username: root
      password: 123456
      database: product_catalog
      authentication-database: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
